### ISSUE TITLE
License

### ISSUE THREAD

**Issue by Pjstaab** [bresheske/openAch#1]
Just wondering if you had any plans on adding a license to this repo, I'm interested in using it. Thanks!

**Comment by bresheske** [comment]
@Pjstaab Here you go sir: https://github.com/bresheske/openAch/blob/master/LICENSE

Feel free to use at your discretion.  The code is mostly just a sub-string parser.

Thanks for your interest!

**Comment by Pjstaab** [comment]
Thank you much! I've ripped out some of the guts, moved to jest for tests, pino for logging, added a bunch of formatting and linting things, left some secret sauce comments, and just generally moved things around for my needs. If you still have any interest in this project I'd be happy to collaborate otherwise I'll keep pushing up changes to my fork.

**Comment by bresheske** [comment]
Rip like crazy man.  If you can make the project better in a generic way, I'm always open to pull requests.  I'm also more of a fan of Jest these days.
